# Generated by Django 2.0.1 on 2020-07-04 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodriver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('best_by', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 19, 44, 17, 479900))),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this pickup was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this pickup was updated. Automatically generated when the model updates.')),
                ('image', models.ImageField(default='default.jpg', upload_to='donation_pics')),
            ],
        ),
        migrations.CreateModel(
            name='TakenPickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('foodriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_pickups', to='classroom.Foodriver')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_pickups', to='classroom.Pickup')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_foodonator',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_foodriver',
        ),
        migrations.AddField(
            model_name='user',
            name='is_shelter',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='Area',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
        migrations.AddField(
            model_name='pickup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodriver',
            name='pickups',
            field=models.ManyToManyField(through='classroom.TakenPickup', to='classroom.Pickup'),
        ),
        migrations.AddField(
            model_name='foodriver',
            name='requirements',
            field=models.ManyToManyField(related_name='interested_foodrivers', to='classroom.Area'),
        ),
    ]
